# Generated by Django 3.0.3 on 2020-04-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='user',
        ),
    ]
